Home: link:/lokalebesturen/139-www.html[HR Oplossingen] |
link:/lokalebesturen/139-www/271-www.html[Opleidingen] |
link:/lokalebesturen/139-www/271-www/419-www.html[Softwaretoepassingen]
|
link:/lokalebesturen/139-www/271-www/419-www/514-www.html[Loonadministratie]

[[dsy350-www]]
Basisopleiding Loonadministratie
--------------------------------

Inhoud van de opleiding
-----------------------

Na een 6-daagse basisopleiding bent u in staat om de volledige
loonverwerking te verrichten.

* De eerste dag van de opleiding worden de begrippen en de terminologie
van het loonprogramma uitgelegd. Ook een overzicht van de algemene
structuur komt aan bod. De hoofdmoot van deze eerste dag bestaat uit de
input van de werknemergegevens, gevolgd door oefeningen over deze
materie.
* De tweede dag komt alles aan bod met betrekking tot de
bezoldigingsregeling.
* De derde dag wordt hoofdzakelijk besteed aan het kalenderbeheer met
een aangepaste oefensessie.
* De vierde dag komen voornamelijk het rekenen van lonen, het doorgeven
van de loongegevens naar de boekhouding en de betalingen aan bod. Ook
wordt aandacht besteed aan de verschillende rapporten en formulieren.
* Op de vijfde en zesde dag wordt o.a. ingegaan op het programma
maaltijdcheques, het aanmaken van een arbeidscyclus, het gebruik van de
sjablonen, de dimona-aangifte en de aangifte van pensioenen. Ook worden
een aantal praktijkgevallen uitgediept. +
 Een herhalingsoefening vormt het sluitstuk van de basisopleiding. 

Voor wie
--------

Nieuwe gebruikers van de softwaretoepassing Loonadministratie of
softwaregebruikers die een herhaling wensen.

Praktisch
---------

* Alle vormingsessies vinden plaats in één van onze opleidingszalen te
Nazareth (Zaal Valk of zaal Arend) of in het auditorium van het
Suikermuseum in Tienen.

Inschrijven
-----------

Inschrijven kan via de klantenzone.

Meer info?
----------

Wenst u meer info over deze opleiding dan kan u Stijn De Vos 
contacteren:

* tel: +32 (09) 389 03 25
* mailto:sdv@schaubroeck.be[e-mail]
