Home: link:/lokalebesturen/139-www.html[HR Oplossingen] |
link:/lokalebesturen/139-www/271-www.html[Opleidingen] |
link:/lokalebesturen/139-www/271-www/419-www.html[Softwaretoepassingen]
|
link:/lokalebesturen/139-www/271-www/419-www/514-www.html[Loonadministratie]

[[dsy2781-www]]
Begroting
---------

Inhoud van de opleiding
-----------------------

* Tijdens deze opleiding behandelen we alle facetten van de
personeelsbegroting
* U kan een begroting voor één of meerdere jaren opmaken. Daarnaast kan
u aanvullende begrotingen of begrotingswijzigingen opmaken en ook
gedurende het jaar controleren of de reële loonkost overeenkomt met de
loonkost die voor dat jaar werd begroot. Er volgt ook een woordje uitleg
bij de verschillende parameters die bij het ramen van de loonkost
gebruikt worden.
* Oefeningen ronden deze sessie af

Voor wie
--------

* Softwaregebruikers van de toepassing loonadministratie die
via de begrotingsmodule een personeelsbegroting opmaken.

Praktisch
---------

* Alle vormingsessies vinden plaats in één van onze opleidingszalen te
Nazareth, Zaal Valk of zaal Arend.

Inschrijven
-----------

* Inschrijven kan via de klantenzone.

Meer info?
----------

Wenst u meer info over deze opleiding dan kan u Stijn De Vos 
contacteren:

* tel: +32 (09) 389 03 25
* mailto:sdv@schaubroeck.be[e-mail]
