(from http://www.schaubroeck.be/lokalebesturen/139-www/271-www/419-www/514-www/494-www.html )

Home: link:/lokalebesturen/139-www.html[HR Oplossingen] |
link:/lokalebesturen/139-www/271-www.html[Opleidingen] |
link:/lokalebesturen/139-www/271-www/419-www.html[Softwaretoepassingen]
|
link:/lokalebesturen/139-www/271-www/419-www/514-www.html[Loonadministratie]

[[dsy494-www]]
DMFAppl-aangifte
----------------

Inhoud van de opleiding
-----------------------

Tijdens de opleiding DMFAppl-aangifte besteden we aandacht aan het
opmaken van een oorspronkelijke DMFAppl-aangifte.

* Eerst bespreken we wat de voorwaarden zijn voor het maken van de
aangifte met de nodige aandacht voor een aantal belangrijke gegevens in
kalender en opdracht.
* Ook de verschillende controles komen uitgebreid aan bod.
* Daarna wordt het volledige proces van de aangifte doorlopen.
* Als laatste behandelen we uitgebreid alle lijsten die o.b.v. de
aangifte kunnen afgedrukt worden.

Voor wie
--------

* softwaregebruikers die betrokken zijn bij het aanmaken van een
DMFAppl-aangifte.

Praktisch
---------

* Alle vormingsessies vinden plaats in één van onze opleidingszalen te
Nazareth, Zaal Valk of zaal Arend.

Documentatie
------------

Inschrijven
-----------

* Inschrijven kan via de klantenzone.

Meer info?
----------

Wenst u meer info over deze opleiding dan kan u Ann Rohaert contacteren:

* tel: +32 (09) 389 03 26
* e-mail:
link:/schaubroeck.be/lokalebesturen/ext/forms/mailing?mailto=ar[contact]
