Home: link:/lokalebesturen/139-www.html[HR Oplossingen] |
link:/lokalebesturen/139-www/271-www.html[Opleidingen] |
link:/lokalebesturen/139-www/271-www/419-www.html[Softwaretoepassingen]
|
link:/lokalebesturen/139-www/271-www/419-www/514-www.html[Loonadministratie]

[[dsy496-www]]
Eindejaarstoelage
-----------------

Inhoud van de opleiding
-----------------------

* In deze opleiding leert u hoe u de eindejaarstoelage met het
loonprogramma kan berekenen.
* Aan de hand van de weddegegevens van de opdracht en de
gelijkstellingen in de kalender wordt voor ieder personeelslid het
correcte bedrag van de eindejaarstoelage berekend.
* Met een kleine oefening kan u het programma in de praktijk uittesten.

Voor wie
--------

* softwaregebruikers van de toepassing Loonadministratie die de
eindejaarstoelage berekenen

Praktisch
---------

* Alle vormingsessies vinden plaats in één van onze opleidingszalen te
Nazareth, Zaal Valk of zaal Arend.

Documentatie
------------

* Bij deze opleiding krijgt u een handleiding

Inschrijven
-----------

* Inschrijven kan via de klantenzone.

Meer info?
----------

Wenst u meer info over deze opleiding dan kan u Stijn De Vos 
contacteren:

* tel: +32 (09) 389 03 25
* mailto:sdv@schaubroeck.be[e-mail]
