Home: link:/lokalebesturen/139-www.html[HR Oplossingen] |
link:/lokalebesturen/139-www/271-www.html[Opleidingen] |
link:/lokalebesturen/139-www/271-www/419-www.html[Softwaretoepassingen]
|
link:/lokalebesturen/139-www/271-www/419-www/514-www.html[Loonadministratie]

[[dsy497-www]]
Fiscale fiches en Belcotax
--------------------------

Inhoud van de opleiding
-----------------------

De opleiding fiscale fiches en Belcotax geeft u informatie over

* het opmaken van een bestand met alle gegevens i.v.m. de fiscale fiches
en het systeem Belcotax. Dit bestand wordt automatisch opgemaakt met de
berekende gegevens voor een fiscaal jaar uit het loonprogramma.
* het aanbrengen van wijzigingen of toevoegingen
* het afdrukken van de individuele fiches voor de personeelsleden

Voor wie
--------

* softwaregebruikers van de toepassing Loonadministratie die de
jaarlijkse fiscale fiches aanmaken. 

Praktisch
---------

* Alle vormingsessies vinden plaats in één van onze opleidingszalen te
Nazareth, Zaal Valk of zaal Arend.

Documentatie
------------

* Bij deze opleiding krijgt u een exemplaar van de powerpoint
presentatie en/of een handleiding fiscale fiches en Belcotax 

Inschrijven
-----------

* Inschrijven kan via de klantenzone.

Meer info?
----------

Wenst u meer info over deze opleiding dan kan u Stijn De Vos 
contacteren:

* tel: +32 (09) 389 03 25
* mailto:sdv@schaubroeck.be[e-mail]
