Home: link:/lokalebesturen/139-www.html[HR Oplossingen] |
link:/lokalebesturen/139-www/271-www.html[Opleidingen] |
link:/lokalebesturen/139-www/271-www/419-www.html[Softwaretoepassingen]
|
link:/lokalebesturen/139-www/271-www/419-www/514-www.html[Loonadministratie]

[[dsy495-www]]
Vakantiegeld
------------

Inhoud van de opleiding
-----------------------

* Tijdens deze opleiding bespreken we alle facetten van het berekenen
van het vakantiegeld en het vakantiegeld wegens uitdiensttreding
* Ook het afdrukken van verschillende lijsten en de attesten voor
vakantiegeld wegens uitdiensttreding komen aan bod
* Oefeningen ronden deze sessie af

Voor wie
--------

* softwaregebruikers van de toepassing loonadministratie die
vakantiegeld en/of vakantiegeld wegens uitdiensttreding berekenen

Praktisch
---------

* Alle vormingsessies vinden plaats in één van onze opleidingszalen te
Nazareth, Zaal Valk of zaal Arend.

Documentatie
------------

* Bij deze opleiding krijgt u een handleiding vakantiegeld en
vakantiegeld wegens uitdiensttreding

Inschrijven
-----------

* Inschrijven kan via de klantenzone.

Meer info?
----------

Wenst u meer info over deze opleiding dan kan u Stijn De Vos 
contacteren:

* tel: +32 (09) 389 03 25
* mailto:sdv@schaubroeck.be[e-mail]
